spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pavanpatent/spider-framework
          searchPaths: spider-framework/config/local

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"